name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm test

  release:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Empaquetar el proyecto
        run: npm pack

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tgz"
          generate_release_notes: true
